// Mocks generated by Mockito 5.0.17 from annotations
// in trivia_game/test/services/api_client_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:trivia_game/services/api_client.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Response<dynamic>?> getAll(
          String? path, Map<String, dynamic>? queryParameters) =>
      (super.noSuchMethod(Invocation.method(#getAll, [path, queryParameters]),
              returnValue: Future<_i4.Response<dynamic>?>.value())
          as _i3.Future<_i4.Response<dynamic>?>);
}
