// Mocks generated by Mockito 5.0.17 from annotations
// in trivia_game/test/contexts/category/category_screen_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trivia_game/contexts/category/category_model.dart' as _i4;
import 'package:trivia_game/contexts/category/category_repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CategoryModel>> fetchCategories() =>
      (super.noSuchMethod(Invocation.method(#fetchCategories, []),
              returnValue:
                  Future<List<_i4.CategoryModel>>.value(<_i4.CategoryModel>[]))
          as _i3.Future<List<_i4.CategoryModel>>);
}
